name: Python Checks

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      run-ci-check:
        required: false
        type: boolean
        default: false

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ inputs.python-version }}
          enable-cache: true

      - name: Sync dependencies
        run: uv sync --frozen --group dev

      - name: Run CI checks
        if: inputs.run-ci-check
        run: make ci-check

      - name: Run tests
        run: make test
